--LIBRARY ieee;
--USE ieee.std_logic_1164.all;
--USE ieee.std_logic_unsigned.all;
--
--ENTITY Top IS
--    PORT (
--        CLOCK_50 : IN STD_LOGIC;                     -- 50 MHz clock
--        KEY      : IN STD_LOGIC_VECTOR(3 DOWNTO 0);  -- Pushbuttons (active low)
--        SW       : IN STD_LOGIC_VECTOR(9 DOWNTO 0);  -- Switches
--        LEDR     : OUT STD_LOGIC_VECTOR(9 DOWNTO 0); -- LEDs
--        HEX0     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- 7-segment display
--        HEX1     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
--        HEX2     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
--        HEX3     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
--        HEX4     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
--        HEX5     : OUT STD_LOGIC_VECTOR(6 DOWNTO 0)
--    );
--END Top;
--
--ARCHITECTURE Behavior OF Top IS
--
--    COMPONENT project
--        PORT (
--            DIN     : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
--            Resetn  : IN STD_LOGIC;
--            Clock   : IN STD_LOGIC;
--            Run     : IN STD_LOGIC;
--            Done    : BUFFER STD_LOGIC;
--            BusOut  : OUT STD_LOGIC_VECTOR(8 DOWNTO 0)
--        );
--    END COMPONENT;
--
--    SIGNAL Done    : STD_LOGIC;
--    SIGNAL BusOut  : STD_LOGIC_VECTOR(8 DOWNTO 0);
--
--    -- 7-segment HEX digit decoder function
--    FUNCTION HexDigitTo7Seg(input : STD_LOGIC_VECTOR(3 DOWNTO 0)) RETURN STD_LOGIC_VECTOR IS
--        VARIABLE seg : STD_LOGIC_VECTOR(6 DOWNTO 0);
--    BEGIN
--        CASE input IS
--            WHEN "0000" => seg := "1000000"; -- 0
--            WHEN "0001" => seg := "1111001"; -- 1
--            WHEN "0010" => seg := "0100100"; -- 2
--            WHEN "0011" => seg := "0110000"; -- 3
--            WHEN "0100" => seg := "0011001"; -- 4
--            WHEN "0101" => seg := "0010010"; -- 5
--            WHEN "0110" => seg := "0000010"; -- 6
--            WHEN "0111" => seg := "1111000"; -- 7
--            WHEN "1000" => seg := "0000000"; -- 8
--            WHEN "1001" => seg := "0010000"; -- 9
--            WHEN "1010" => seg := "0001000"; -- A
--            WHEN "1011" => seg := "0000011"; -- B
--            WHEN "1100" => seg := "1000110"; -- C
--            WHEN "1101" => seg := "0100001"; -- D
--            WHEN "1110" => seg := "0000110"; -- E
--            WHEN "1111" => seg := "0001110"; -- F
--            WHEN OTHERS => seg := "1111111"; -- All OFF
--        END CASE;
--        RETURN seg;
--    END FUNCTION;
--
--BEGIN
--
--    -- Instantiate the processor
--    U1: project PORT MAP (
--        DIN     => SW(8 DOWNTO 0),   -- SW0–SW8: instruction/data input
--        Resetn  => KEY(0),           -- KEY0: Reset (active low)
--        Clock   => CLOCK_50,         -- 50 MHz board clock
--        Run     => NOT KEY(1),       -- KEY1: Run (active high), invert because KEY is active low
--        Done    => Done,
--        BusOut  => BusOut
--    );
--
--    -- Show output on LEDs
--    LEDR(8 DOWNTO 0) <= BusOut;
--    LEDR(9) <= Done;
--
--    -- Show BusOut on HEX displays
--    HEX0 <= HexDigitTo7Seg(BusOut(3 DOWNTO 0)); -- Low nibble
--    HEX1 <= HexDigitTo7Seg(BusOut(7 DOWNTO 4)); -- High nibble
--    HEX2 <= "1111111";
--    HEX3 <= "1111111";
--    HEX4 <= "1111111";
--    HEX5 <= "1111111";
--
--END Behavior;
